[build]
command = "npm install --legacy-peer-deps && npm run build"
publish = ".next/static"
functions = ".next/server"

[build.environment]
NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-nextjs"
